import { boolean, integer, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), role: text('role').notNull().default('client'), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const trainingType = pgTable('training_type', { id: text('id').primaryKey(), name: text('name').notNull(), description: text('description').notNull(), durationMinutes: integer('durationMinutes').notNull().default(60), capacity: integer('capacity').notNull().default(1), price: integer('price').notNull().default(0), active: boolean('active').notNull().default(true) })
export const timeSlot = pgTable('time_slot', { id: text('id').primaryKey(), trainingTypeId: text('trainingTypeId').notNull(), startsAt: timestamp('startsAt').notNull(), endsAt: timestamp('endsAt').notNull(), capacity: integer('capacity').notNull().default(1), status: text('status').notNull().default('available') })
export const booking = pgTable('booking', { id: text('id').primaryKey(), userId: text('userId').notNull(), timeSlotId: text('timeSlotId').notNull(), status: text('status').notNull().default('confirmed'), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() }, (table) => ({ userSlotUnique: uniqueIndex('booking_user_slot_unique').on(table.userId, table.timeSlotId) }))
export const profile = pgTable('profile', { userId: text('userId').primaryKey(), phone: text('phone'), goals: text('goals'), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
