import Link from 'next/link'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import { and, desc, eq } from 'drizzle-orm'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { booking, profile, timeSlot, trainingType, user } from '@/lib/db/schema'
import { ClientCalendar } from '@/components/client-calendar'
import { SignOutButton } from '@/components/sign-out-button'

export default async function AccountPage() {
  const session = await auth.api.getSession({ headers: await headers() })
  if (!session?.user) redirect('/sign-in')
  const [accountUser] = await db.select({ role: user.role }).from(user).where(eq(user.id, session.user.id)).limit(1)
  const rows = await db.select({ booking, slot: timeSlot, training: trainingType }).from(booking).innerJoin(timeSlot, eq(booking.timeSlotId, timeSlot.id)).innerJoin(trainingType, eq(timeSlot.trainingTypeId, trainingType.id)).where(and(eq(booking.userId, session.user.id), eq(booking.status, 'confirmed'))).orderBy(desc(timeSlot.startsAt))
  const existingProfile = await db.select().from(profile).where(eq(profile.userId, session.user.id)).limit(1)
  const reservations = rows.map(({ booking: item, slot, training }) => ({ id: item.id, startsAt: slot.startsAt.toISOString(), endsAt: slot.endsAt.toISOString(), training: training.name, status: item.status }))
  return <main className="reservation-page reservation-calendar min-h-screen"><header className="flex flex-wrap items-center justify-between gap-5 border-b border-white/15 bg-black/25 px-6 py-6 lg:px-10"><Link href="/" className="font-mono text-sm font-bold tracking-[0.18em]">PGL<span className="text-accent">.</span>TRAINNING</Link><div className="flex flex-wrap items-center gap-5"><Link href="/" className="text-sm font-semibold">Inicio</Link>{accountUser?.role === 'admin' && <Link href="/admin" className="text-sm font-semibold">Panel Admin</Link>}<Link href="/reservar" className="text-sm font-semibold">Reservar sesión</Link><SignOutButton className="text-sm font-semibold" /></div></header><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10"><p className="font-mono text-xs uppercase tracking-[0.2em] text-accent">Dashboard cliente</p><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-5xl font-bold tracking-[-0.06em]">Hola, {session.user.name}.</h1><p className="mt-4 text-muted-foreground">Consulta tus reservas y reserva tu próxima sesión.</p></div><Link href="/mi-cuenta/perfil" className="text-sm font-semibold underline underline-offset-4">Editar perfil</Link></div><div className="mt-14"><ClientCalendar reservations={reservations} /></div><section className="mt-6 rounded-2xl border border-white/15 bg-background/85 p-7 backdrop-blur-md"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-bold tracking-[-0.04em]">Próximas sesiones</h2><Link href="/reservar" className="text-xs font-bold uppercase tracking-[0.12em] text-accent">Nueva reserva</Link></div>{rows.length === 0 ? <p className="mt-10 text-sm text-muted-foreground">Todavía no tienes sesiones reservadas.</p> : <div className="mt-8 flex flex-col gap-4">{rows.map(({ booking: item, slot, training }) => <div key={item.id} className="flex flex-col justify-between gap-4 border-t border-border pt-5 sm:flex-row"><div><p className="font-mono text-xs uppercase tracking-[0.14em] text-accent">{new Intl.DateTimeFormat('es-ES', { dateStyle: 'full' }).format(slot.startsAt)}</p><p className="mt-2 font-semibold">{training.name}</p><p className="mt-1 text-sm text-muted-foreground">{new Intl.DateTimeFormat('es-ES', { hour: '2-digit', minute: '2-digit' }).format(slot.startsAt)} · Calle San Blas 15</p></div><span className="self-start border border-border px-3 py-2 text-xs font-bold uppercase tracking-[0.12em]">Confirmada</span></div>)}</div>}</section><div className="mt-6 flex justify-end"><p className="text-xs text-muted-foreground">{existingProfile[0]?.phone ? `Contacto: ${existingProfile[0].phone}` : 'Añade tus datos de contacto desde tu perfil.'}</p></div></div></main>
}
